const $=id=>document.getElementById(id);const num=id=>parseFloat($(id).value);const f=(v,n=3)=>Number.isFinite(v)?v.toFixed(n):'-';
let points=JSON.parse(localStorage.getItem('survey_points')||'[]');let watchId=null,currentGps=null,currentXY=null,target=null,heading=null;
const zones={1:[33,129.5],2:[33,131],3:[36,132+10/60],4:[33,133.5],5:[36,134+20/60],6:[36,136],7:[36,137+10/60],8:[36,138.5],9:[36,139+50/60],10:[40,140+50/60],11:[44,140.25],12:[44,142.25],13:[44,144.25],14:[26,142],15:[26,127.5],16:[26,124],17:[26,131],18:[20,136],19:[26,154]};
for(let i=1;i<=19;i++){const o=document.createElement('option');o.value=i;o.textContent=`第${roman(i)}系`;if(i===6)o.selected=true;$('zone').appendChild(o)}
function roman(n){return ['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX'][n]}
function zoneNo(){return +$('zone').value}
const a=6378137,invF=298.257222101,ff=1/invF,e2=ff*(2-ff),ep2=e2/(1-e2),k0=.9999;
function meridional(phi){const e4=e2*e2,e6=e4*e2;return a*((1-e2/4-3*e4/64-5*e6/256)*phi-(3*e2/8+3*e4/32+45*e6/1024)*Math.sin(2*phi)+(15*e4/256+45*e6/1024)*Math.sin(4*phi)-(35*e6/3072)*Math.sin(6*phi))}
function llToXY(lat,lon,z=zoneNo()){const [lat0d,lon0d]=zones[z],p=lat*Math.PI/180,l=lon*Math.PI/180,p0=lat0d*Math.PI/180,l0=lon0d*Math.PI/180,s=Math.sin(p),c=Math.cos(p),t=Math.tan(p),N=a/Math.sqrt(1-e2*s*s),T=t*t,C=ep2*c*c,A=(l-l0)*c,M=meridional(p),M0=meridional(p0);const x=k0*(M-M0+N*t*(A*A/2+(5-T+9*C+4*C*C)*A**4/24+(61-58*T+T*T+600*C-330*ep2)*A**6/720));const y=k0*N*(A+(1-T+C)*A**3/6+(5-18*T+T*T+72*C-58*ep2)*A**5/120);return{x,y}}
function xyToLL(x,y,z=zoneNo()){const [lat0d,lon0d]=zones[z],p0=lat0d*Math.PI/180,l0=lon0d*Math.PI/180,M0=meridional(p0),M=M0+x/k0,e1=(1-Math.sqrt(1-e2))/(1+Math.sqrt(1-e2)),mu=M/(a*(1-e2/4-3*e2*e2/64-5*e2**3/256));const p1=mu+(3*e1/2-27*e1**3/32)*Math.sin(2*mu)+(21*e1**2/16-55*e1**4/32)*Math.sin(4*mu)+(151*e1**3/96)*Math.sin(6*mu)+(1097*e1**4/512)*Math.sin(8*mu),s=Math.sin(p1),c=Math.cos(p1),t=Math.tan(p1),N=a/Math.sqrt(1-e2*s*s),R=a*(1-e2)/(1-e2*s*s)**1.5,T=t*t,C=ep2*c*c,D=y/(N*k0);const p=p1-(N*t/R)*(D*D/2-(5+3*T+10*C-4*C*C-9*ep2)*D**4/24+(61+90*T+298*C+45*T*T-252*ep2-3*C*C)*D**6/720);const l=l0+(D-(1+2*T+C)*D**3/6+(5-2*C+28*T-3*C*C+8*ep2+24*T*T)*D**5/120)/c;return{lat:p*180/Math.PI,lon:l*180/Math.PI}}
function save(){localStorage.setItem('survey_points',JSON.stringify(points));renderPoints();drawMap()}
function renderPoints(){const html=points.length?points.map((p,i)=>`${i+1}. ${p.name}  X=${f(p.x)} Y=${f(p.y)} Z=${f(p.z)}`).join('\n'):'保存済み測点はありません';$('pointsList').textContent=html;['pA','pB','targetPoint'].forEach(id=>{$(id).innerHTML=points.map((p,i)=>`<option value="${i}">${p.name}</option>`).join('')});if(points.length>1)$('pB').value='1'}
function updateGpsUI(){if(!currentGps||!currentXY)return;$('gpsLat').textContent=f(currentGps.lat,7);$('gpsLon').textContent=f(currentGps.lon,7);$('gpsAcc').textContent=`±${f(currentGps.accuracy,1)} m`;$('gpsAlt').textContent=Number.isFinite(currentGps.altitude)?`${f(currentGps.altitude,2)} m`:'取得なし';$('gpsX').textContent=`${f(currentXY.x)} m`;$('gpsY').textContent=`${f(currentXY.y)} m`;$('gpsStatus').textContent=`GPS取得中 / 第${roman(zoneNo())}系 / ${new Date().toLocaleTimeString()}`;updateStakeout();drawMap()}
function gotPos(pos){currentGps={lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy,altitude:pos.coords.altitude};currentXY=llToXY(currentGps.lat,currentGps.lon);updateGpsUI()}
function gpsErr(e){$('gpsStatus').textContent=`GPSエラー: ${e.message}`}
$('startGps').onclick=()=>{if(!navigator.geolocation){gpsErr({message:'この端末では位置情報を利用できません'});return}if(watchId!==null)navigator.geolocation.clearWatch(watchId);const opts={enableHighAccuracy:true,maximumAge:0,timeout:15000};if($('gpsMode').value==='once')navigator.geolocation.getCurrentPosition(gotPos,gpsErr,opts);else watchId=navigator.geolocation.watchPosition(gotPos,gpsErr,opts)};
$('stopGps').onclick=()=>{if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;$('gpsStatus').textContent='GPS停止中'};
$('zone').onchange=()=>{if(currentGps){currentXY=llToXY(currentGps.lat,currentGps.lon);updateGpsUI()}drawMap()};
$('startCompass').onclick=async()=>{try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const r=await DeviceOrientationEvent.requestPermission();if(r!=='granted')throw new Error('コンパス許可がありません')}window.addEventListener('deviceorientation',orientationHandler,true);$('startCompass').textContent='コンパスON'}catch(e){alert('コンパスを開始できません: '+e.message)}};
function orientationHandler(e){if(Number.isFinite(e.webkitCompassHeading))heading=e.webkitCompassHeading;else if(Number.isFinite(e.alpha))heading=(360-e.alpha)%360;updateStakeout()}
$('saveGpsPoint').onclick=()=>{if(!currentXY){alert('先にGPSを開始してください');return}const name=`GPS-${new Date().toLocaleTimeString().replace(/:/g,'')}`;points.push({name,x:currentXY.x,y:currentXY.y,z:Number.isFinite(currentGps.altitude)?currentGps.altitude:0,lat:currentGps.lat,lon:currentGps.lon,accuracy:currentGps.accuracy});save();alert(`${name} を保存しました`)};
$('openAppleMaps').onclick=()=>{if(!currentGps){alert('先にGPSを開始してください');return}location.href=`https://maps.apple.com/?ll=${currentGps.lat},${currentGps.lon}&q=現在地`};$('centerMap').onclick=drawMap;
$('addPoint').onclick=()=>{const p={name:$('ptName').value.trim()||`P${points.length+1}`,x:num('ptX'),y:num('ptY'),z:num('ptZ')};if(!Number.isFinite(p.x)||!Number.isFinite(p.y)){alert('XとYを入力してください');return}if(!Number.isFinite(p.z))p.z=0;points.push(p);save()};
$('loadTarget').onclick=()=>{if(!points.length){alert('保存測点がありません');return}const p=points[+$('targetPoint').value];$('targetName').value=p.name;$('targetX').value=f(p.x);$('targetY').value=f(p.y)};
$('setTarget').onclick=()=>{const x=num('targetX'),y=num('targetY');if(!Number.isFinite(x)||!Number.isFinite(y)){alert('目的X・Yを入力してください');return}target={name:$('targetName').value.trim()||'杭出し点',x,y};updateStakeout();drawMap()};
function updateStakeout(){if(!target||!currentXY){$('stakeDistance').textContent='-';$('stakeAz').textContent='-';$('stakeTurn').textContent='-';return}const dx=target.x-currentXY.x,dy=target.y-currentXY.y,d=Math.hypot(dx,dy),az=(Math.atan2(dy,dx)*180/Math.PI+360)%360;$('stakeDistance').textContent=`${f(d,2)} m`;$('stakeAz').textContent=`${f(az,1)}°`;let turn='コンパス未使用';if(Number.isFinite(heading)){let delta=((az-heading+540)%360)-180;turn=`${delta>=0?'右':'左'} ${f(Math.abs(delta),1)}°`}$('stakeTurn').textContent=turn;$('stakeDetail').textContent=`目的点: ${target.name}\n現在 X=${f(currentXY.x)} Y=${f(currentXY.y)}\n目的 X=${f(target.x)} Y=${f(target.y)}\n北方向差 ΔX=${f(dx)} m\n東方向差 ΔY=${f(dy)} m\nGPS推定精度 ±${f(currentGps?.accuracy,1)} m`}
function drawMap(){const c=$('fieldMap'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#f8fafc';ctx.fillRect(0,0,w,h);const all=points.map(p=>({x:p.x,y:p.y,type:'p',name:p.name}));if(currentXY)all.push({...currentXY,type:'c',name:'現在地'});if(target)all.push({...target,type:'t'});if(!all.length){ctx.fillStyle='#64748b';ctx.font='28px sans-serif';ctx.textAlign='center';ctx.fillText('GPSまたは測点を登録してください',w/2,h/2);return}let minX=Math.min(...all.map(p=>p.x)),maxX=Math.max(...all.map(p=>p.x)),minY=Math.min(...all.map(p=>p.y)),maxY=Math.max(...all.map(p=>p.y));let span=Math.max(maxX-minX,maxY-minY,20);const pad=70,scale=Math.min((w-2*pad)/span,(h-2*pad)/span),cx=(minX+maxX)/2,cy=(minY+maxY)/2;const px=p=>w/2+(p.y-cy)*scale,py=p=>h/2-(p.x-cx)*scale;ctx.strokeStyle='#e2e8f0';ctx.lineWidth=1;for(let i=0;i<=10;i++){const xx=i*w/10,yy=i*h/10;ctx.beginPath();ctx.moveTo(xx,0);ctx.lineTo(xx,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke()}ctx.fillStyle='#111827';ctx.font='bold 24px sans-serif';ctx.textAlign='left';ctx.fillText('N ↑',18,34);for(const p of all){const x=px(p),y=py(p);ctx.lineWidth=4;if(p.type==='c'){ctx.fillStyle='#2563eb';ctx.beginPath();ctx.arc(x,y,10,0,Math.PI*2);ctx.fill()}else if(p.type==='t'){ctx.strokeStyle='#dc2626';ctx.beginPath();ctx.moveTo(x-12,y);ctx.lineTo(x+12,y);ctx.moveTo(x,y-12);ctx.lineTo(x,y+12);ctx.stroke()}else{ctx.strokeStyle='#475569';ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#111827';ctx.font='18px sans-serif';ctx.fillText(p.name||'',x+12,y-10)}if(currentXY&&target){ctx.strokeStyle='#111827';ctx.setLineDash([10,8]);ctx.beginPath();ctx.moveTo(px(currentXY),py(currentXY));ctx.lineTo(px(target),py(target));ctx.stroke();ctx.setLineDash([])}const scaleM=Math.max(1,Math.round(100/scale));const len=scaleM*scale;ctx.strokeStyle='#111827';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(30,h-35);ctx.lineTo(30+len,h-35);ctx.stroke();ctx.font='16px sans-serif';ctx.fillText(`${scaleM} m`,30,h-45)}
$('llToXy').onclick=()=>{const lat=num('convLat'),lon=num('convLon');if(!Number.isFinite(lat)||!Number.isFinite(lon)){alert('緯度・経度を入力してください');return}const q=llToXY(lat,lon);$('convX').value=f(q.x);$('convY').value=f(q.y);$('convResult').textContent=`第${roman(zoneNo())}系\nX=${f(q.x)} m\nY=${f(q.y)} m`};
$('xyToLl').onclick=()=>{const x=num('convX'),y=num('convY');if(!Number.isFinite(x)||!Number.isFinite(y)){alert('X・Yを入力してください');return}const q=xyToLL(x,y);$('convLat').value=f(q.lat,8);$('convLon').value=f(q.lon,8);$('convResult').textContent=`第${roman(zoneNo())}系\n緯度=${f(q.lat,8)}°\n経度=${f(q.lon,8)}°`};
$('calcPair').onclick=()=>{if(points.length<2){$('pairResult').textContent='測点を2点以上登録してください';return}const A=points[+$('pA').value],B=points[+$('pB').value],dx=B.x-A.x,dy=B.y-A.y,dz=B.z-A.z,hh=Math.hypot(dx,dy),s=Math.hypot(hh,dz),az=(Math.atan2(dy,dx)*180/Math.PI+360)%360,g=hh?dz/hh*100:0;$('pairResult').textContent=`水平距離 ${f(hh)} m\n斜距離 ${f(s)} m\n高低差 ${f(dz)} m\n方向角 ${f(az,4)}°\n勾配 ${f(g,3)} %${Math.abs(dz)>1e-9?`\n1 : ${f(hh/Math.abs(dz),2)}`:''}`};
$('calcStake').onclick=()=>{const x=num('baseX'),y=num('baseY'),az=num('az')*Math.PI/180,along=num('along'),off=num('offset');if([x,y,az,along,off].some(v=>!Number.isFinite(v))){$('stakeResult').textContent='すべて入力してください';return}const nx=x+along*Math.cos(az)-off*Math.sin(az),ny=y+along*Math.sin(az)+off*Math.cos(az);$('stakeResult').textContent=`計算座標\nX = ${f(nx)}\nY = ${f(ny)}`};
$('calcArea').onclick=()=>{const pts=$('poly').value.trim().split(/\n+/).map(r=>r.split(',').map(Number)).filter(a=>a.length>=2&&a.every(Number.isFinite));if(pts.length<3){$('areaResult').textContent='3点以上入力してください';return}let s=0;for(let i=0;i<pts.length;i++){const[x1,y1]=pts[i],[x2,y2]=pts[(i+1)%pts.length];s+=x1*y2-x2*y1}$('areaResult').textContent=`面積 = ${f(Math.abs(s)/2)} m²`};
$('calcCurve').onclick=()=>{const x=num('bcX'),y=num('bcY'),az0=num('bcAz')*Math.PI/180,R=num('radius'),bc=num('bcSta'),t=num('targetSta'),lw=num('leftW'),rw=num('rightW'),sgn=$('curveDir').value==='R'?1:-1;if([x,y,az0,R,bc,t,lw,rw].some(v=>!Number.isFinite(v))||R<=0){$('curveResult').textContent='入力値を確認してください';return}const s=t-bc,theta=s/R,cx=x+sgn*R*Math.sin(az0),cy=y-sgn*R*Math.cos(az0),phi0=az0-sgn*Math.PI/2,phi=phi0+sgn*theta,px=cx+R*Math.cos(phi),py=cy+R*Math.sin(phi),taz=az0+sgn*theta,lx=px-lw*Math.sin(taz),ly=py+lw*Math.cos(taz),rx=px+rw*Math.sin(taz),ry=py-rw*Math.cos(taz);$('curveResult').textContent=`センター X=${f(px)} Y=${f(py)}\n接線方向角 ${f((taz*180/Math.PI+360)%360,4)}°\n左端 X=${f(lx)} Y=${f(ly)}\n右端 X=${f(rx)} Y=${f(ry)}`};
$('calcGrade').onclick=()=>{const s0=num('gradeSta0'),z0=num('gradeZ0'),g=num('gradePct')/100,s=num('gradeTarget'),ex=num('existingZ');if([s0,z0,g,s].some(v=>!Number.isFinite(v))){$('gradeResult').textContent='入力値を確認してください';return}const z=z0+(s-s0)*g;let txt=`計画高 = ${f(z)} m`;if(Number.isFinite(ex)){const d=z-ex;txt+=`\n現況との差 = ${f(d)} m\n${d>=0?'盛土':'切土'} ${f(Math.abs(d))} m`}$('gradeResult').textContent=txt};
$('calcVCurve').onclick=()=>{const sv=num('vpiSta'),zv=num('vpiZ'),g1=num('g1')/100,g2=num('g2')/100,L=num('vcl'),s=num('vTarget'),ex=num('vExisting');if([sv,zv,g1,g2,L,s].some(v=>!Number.isFinite(v))||L<=0){$('vCurveResult').textContent='入力値を確認してください';return}const pvc=sv-L/2,pvt=sv+L/2,zpvc=zv-g1*L/2;let z;if(s<pvc)z=zpvc+g1*(s-pvc);else if(s>pvt){const zpvt=zpvc+g1*L+(g2-g1)*L/2;z=zpvt+g2*(s-pvt)}else{const x=s-pvc;z=zpvc+g1*x+((g2-g1)/(2*L))*x*x}let txt=`PVC = ${f(pvc)} m\nPVT = ${f(pvt)} m\n計画高 = ${f(z)} m`;if(Number.isFinite(ex)){const d=z-ex;txt+=`\n現況との差 = ${f(d)} m\n${d>=0?'盛土':'切土'} ${f(Math.abs(d))} m`}$('vCurveResult').textContent=txt};
$('exportCsv').onclick=()=>{let csv='測点名,X,Y,Z,緯度,経度,GPS推定精度\n'+points.map(p=>`${p.name},${p.x},${p.y},${p.z},${p.lat??''},${p.lon??''},${p.accuracy??''}`).join('\n');const blob=new Blob([new Uint8Array([0xEF,0xBB,0xBF]),csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SurveyPoints_GPS.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('clearAll').onclick=()=>{if(confirm('保存した測点をすべて削除しますか？')){points=[];save()}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');renderPoints();drawMap();
